---
version: "3.9"
name: procurement-dev
services:
  postgres-local:
    container_name: postgres-local
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: kg-procurement
    volumes:
      - postgres-local:/var/lib/postgresql/data

  pgadmin-local:
    container_name: pgadmin-local
    image: dpage/pgadmin4
    restart: always
    ports:
      - "15432:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-local:/var/lib/pgadmin

  redis-local:
    container_name: "redis-local"
    image: "redis:latest"
    ports:
      - "6379:6379"
    command: redis-server --requirepass password
    environment:
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      REDIS_PASSWORD: password

volumes:
  postgres-local:
  pgadmin-local:
    driver: local
  redis-local: