---
version: "3.9"
name: procurement-dev
services:
  postgres-local:
    container_name: postgres-local
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: kg-procurement
    volumes:
      - postgres-local:/var/lib/postgresql/data

  pgadmin-local:
    container_name: pgadmin-local
    image: dpage/pgadmin4
    restart: always
    ports:
      - "15432:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-local:/var/lib/pgadmin

  server:
    build:
      context: .
    ports:
      - "7070:7070"
    depends_on:
      - postgres-local
    volumes:
      - ./config.jsonc:/work/config.jsonc

volumes:
  postgres-local:
  pgadmin-local:
    driver: local
