name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  test:
    needs: build
    uses: ./.github/workflows/unit-tests.yml

  sonarcloud:
    needs: test
    uses: ./.github/workflows/sonarcloud.yml
